#Cisco IOS 12.2 Hardening Playbook
#
#+ no service pad
#+ ip ssh version 2
#+ no ip domain-lookup
#+ no ip http server
#+ no ip http secure-server
#+ no cdp run
#+ transport input ssh
#+ logging buffered 15000
#+ service password-encryption


- hosts: ios
  remote_user: pi
  become: yes
  become_method: enable
  connection: network_cli

  tasks:
  - name: SHOW RUN | BEG VTY
    ios_command:
      authorize: yes
      commands:
        - show run | beg vty
    register: before_vty
 
  - debug: var=before_vty.stdout_lines
 
  - name: NO SERVICE PAD
    ios_config:
      authorize: yes
      lines:
        - no service pad

  - name: IP SSH VERSION 2
    ios_config:
      authorize: yes
      lines:
        - ip ssh version 2

  - name: NO IP DOMAIN-LOOKUP
    ios_config:
      authorize: yes
      lines:
        - no ip domain-lookup

  - name: DISABLE HTTP/HTTPS MANAGMENT
    ios_config:
      authorize: yes
      lines:
        - no ip http server
        - no ip http secure-server

  - name: DISABLE CDP 
    ios_config:
      authorize: yes
      lines:
        - no cdp run

  - name: TRANSPORT INPUT SSH
    ios_config:
      authorize: yes
      lines:
        - line vty 0 15
        - transport input ssh

  - name: LOGGING BUFFERED 15000
    ios_config:
      authorize: yes
      lines:
        - logging buffered 15000

  - name: SERVICE PASSWORD ENCRYPTION
    ios_config:
      authorize: yes
      lines:
        - service password-encryption
        
  - name: SHOW RUN | BEG VTY
    ios_command:
      authorize: yes
      commands:
        - show run | beg vty
    register: after_vty
 
  - debug: var=after_vty.stdout_lines
