---

- hosts: ios
  remote_user: pi
  become: yes
  become_method: enable
  connection: network_cli


  tasks:
  - name: SHOW RUN | I SSH
    ios_command:
      authorize: yes
      commands:
        - show run | i ssh
    register: before_v2

  - debug: var=before_v2.stdout_lines

  - name: IP SSH VERSION 2
    ios_config:
      authorize: yes
      lines:
        - ip ssh version 2

  - name: SHOW RUN | I SSH
    ios_command:
      authorize: yes
      commands:
        - show run | i ssh
    register: after_v2

  - debug: var=after_v2.stdout_lines

