---

- hosts: ios
  remote_user: pi
  become: yes
  become_method: enable
  connection: network_cli
 
  tasks: 
  - name: CHANGE VTP MODE
    ios_config:
      authorize: yes
      lines:
        - vtp mode transparent
      
  - name: SHOW VTP STATUS
    ios_command:
      authorize: yes
      commands:
        - show vtp status 
    register: after_vtp
 
  - debug: var=after_vtp.stdout_lines
