---
- name: ios
  hosts: all
  gather_facts: no
  connection: network_cli


  tasks:

  - name: SHOW RUN | INC SNMP ON {{ ansible_ssh_host }}
    ios_command:
      commands:
        - show run | i snmp
    register: before_snmp
 
  - debug: var=before_snmp.stdout_lines
 
  - name: SET COMMUNITY STRING ON {{ ansible_ssh_host }}
    ios_config:
      lines:
        - snmp-server community thenetwork.engineer

  - name: TRAP-SOURCE LOOPBACK0 ON {{ ansible_ssh_host }}
    ios_config:
      lines:
         - int lo0
         - snmp-server trap-source Loopback0

  - name: SET CONTACT INFO ON {{ ansible_ssh_host }}
    ios_config:
      lines:
        - snmp-server contact colin@thenetwork.engineer

  - name: ENABLE TRAPS ON {{ ansible_ssh_host }}
    ios_config:
      lines:
        - snmp-server enable traps ospf state-change
        - snmp-server enable traps ospf errors
        - snmp-server enable traps ospf retransmit
        - snmp-server enable traps ospf lsa
        - snmp-server enable traps ospf cisco-specific errors
        - snmp-server enable traps ospf cisco-specific retransmit
        - snmp-server enable traps ospf cisco-specific lsa


  - name: SET SNMP SERVER ADDRESS ON {{ ansible_ssh_host }}
    ios_config:
      lines:
        - snmp-server host 192.168.161.25 pwdhere


  - name: SHOW RUN | INC SNMP ON {{ ansible_ssh_host }}
    ios_command:
      commands:
        - show run | i snmp
    register: after_snmp
 
  - debug: var=after_snmp.stdout_lines

