---

- hosts: ios
  remote_user: pi
  become: yes
  become_method: enable
  connection: network_cli

  tasks:
  - name: TELNET CHECK
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
        - show run | beg line vty
    register: vty

  - debug: var=vty.stdout_lines
