---

- src: https://github.com/colin-mccarthy/ansible_cisco_ios_12.2_hardening_role.git
  name: ansible_cisco_ios_12.2_hardening_role
  scm: git
  version: master
  
- src: https://github.com/colin-mccarthy/ansible_cisco_ios_12.2_hardening_w-template.git
  name: ansible_cisco_ios_12.2_hardening_w-template
  scm: git
  version: master
  
  
 
