---
minor_changes:
  - Add name option for textfsm to create facts to key `network-engine#202 <https://github.com/ansible-network/network-engine/pull/202>`_.
  - Document name option for textfsm in cli plugin and update cli task `network-engine#205 <https://github.com/ansible-network/network-engine/pull/205>`_.
